apiVersion: v1
kind: Namespace
metadata:
  name: expenses

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensesapp
  namespace: expenses
  labels:
    app: expensesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensesapp
  template:
    metadata:
      labels:
        app: expensesapp
    spec:
      containers:
      - name: expensesapp
        image: diptishegar/expensestracker:v1
        ports:
        - containerPort: 8080
        env:
        - name : SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/expenses_tracker
        - name : SPRING_DATASOURCE_USERNAME
          value: "root"
        - name : SPRING_DATASOURCE_PASSWORD
          value: "Test@123"